trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'emilyw26/pipelines-docker'
  dockerHub: 'personal-docker'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile
    tags: test1
- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: |
      $(dockerHub)
    repository: $(imageName)
    command: push
    tags: test1
